# coding: utf-8

"""
    PartSearch Api

    Search for products and retrieve details and pricing.  # noqa: E501

    OpenAPI spec version: Ps2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.part_search_api import PartSearchApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPartSearchApi(unittest.TestCase):
    """PartSearchApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.part_search_api.PartSearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_categories(self):
        """Test case for categories

        Returns all Product Categories. Category Id can be used in KeywordSearchRequest.Filters.TaxonomyIds to restrict a  keyword search to a given category  # noqa: E501
        """
        pass

    def test_categories_by_id(self):
        """Test case for categories_by_id

        Returns Category for given Id. Category Id can be used in KeywordSearchRequest.Filters.TaxonomyIds to restrict a  keyword search to a given category  # noqa: E501
        """
        pass

    def test_digi_reel_pricing(self):
        """Test case for digi_reel_pricing

        Calculate the DigiReel pricing for the given DigiKeyPartNumber and RequestedQuantity  # noqa: E501
        """
        pass

    def test_keyword_search(self):
        """Test case for keyword_search

        KeywordSearch can search for any product in the Digi-Key catalog.  # noqa: E501
        """
        pass

    def test_manufacturer_product_details(self):
        """Test case for manufacturer_product_details

        Create list of ProductDetails from the matches of the requested manufacturer product name.  # noqa: E501
        """
        pass

    def test_manufacturers(self):
        """Test case for manufacturers

        Returns all Product Manufacturers. ManufacturersId can be used in KeywordSearchRequest.Filters.ManufacturerIds to  restrict a keyword search to a given Manufacturer  # noqa: E501
        """
        pass

    def test_product_details(self):
        """Test case for product_details

        Retrieve detailed product information including real time pricing and availability.  # noqa: E501
        """
        pass

    def test_suggested_parts(self):
        """Test case for suggested_parts

        Retrieve detailed product information and two suggested products  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
