# coding: utf-8

"""
    PartSearch Api

    Search for products and retrieve details and pricing.  # noqa: E501

    OpenAPI spec version: Ps2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.limited_parameter import LimitedParameter  # noqa: E501
from swagger_client.rest import ApiException


class TestLimitedParameter(unittest.TestCase):
    """LimitedParameter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLimitedParameter(self):
        """Test LimitedParameter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.limited_parameter.LimitedParameter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
